### ISSUE TITLE
Internal links vs URL coloring

### ISSUE THREAD

**Issue by Owlf-Dev** [lnbgc/obsidian-jotter#1]
Is there any chance of having the option to change the color the URL within style settings? It's hard to distinguish between internal Obsidian links vs external hyperlinks given the same color. It was hard to identify where that could be manually configured within the CSS. Thanks!

**Comment by lnbgc** [comment]
Hi! Sure thing, will look into how to add this option in Style Settings!
Will keep you updated once the fix is available!

**Comment by Owlf-Dev** [comment]
Great thank you so much!

**Comment by lnbgc** [comment]
Hi again! 
Just released the new feature, so make sure to update your theme!
You'll find it in the Typography > Hyperlinks tab in your Style Settings plugin. By default, the links colors remain the same as your accent color, but now you can also pick custom ones for both internal and external links.
Thanks for the feedback and using Jotter, I really appreciate it!

**Comment by Owlf-Dev** [comment]
Awesome thank you so much! This is EXACTLY what I needed. This theme rocks!

**Comment by lnbgc** [comment]
My pleasure ehe, thank you so much!!
